AdminManagement/Areas/Admin/Controllers/Sys/AppLogController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Model;

namespace AdminManagement.Areas.Admin.Controllers.Sys
{

    using global::Model;
    using BLL;
    using Newtonsoft.Json;
    using DbFrame.Class;
    using System.Collections;
    using Microsoft.AspNetCore.Http;
    using AOP;
    using Common;

    public class AppLogController : BaseController
    {
        Sys_AppLogBL _AppLogBL = new Sys_AppLogBL();

        protected override void Init() {


            this.MenuID = "Z-170";
        }

        /// <summary>
        /// 获取数据列表
        /// </summary>
        /// <param name="query"></param>
        /// <param name="page">PageIndex</param>
        /// <param name="rows">PageSize</param>
        /// <returns></returns>
        [NonAction]
        public override Sys_PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            return _AppLogBL.GetDataSource(query, page, rows);
        }
        public IActionResult Find(string ID) {


            return Json(_AppLogBL.Find(ID.ToGuid()));
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}

    }
}

AdminManagement/Areas/Admin/Controllers/Sys/ChangePwdController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
namespace AdminManagement.Areas.Admin.Controllers.Sys
{
    using global::Model;
    using Common;
    public class ChangePwdController :BaseController
    {
        Sys_UserM _Sys_UserM = new Sys_UserM();
        protected override void Init()
        {
           this.MenuID="Z-150";  
        }
        public override IActionResult Index()
        {

            _Sys_UserM = db.Find<Sys_UserM>(f => f.User_ID == Account.UserID);
            ViewData["UserName"] = _Sys_UserM.User_Name;
            ViewData["User_LoginName"] = _Sys_UserM.User_LoginName;
            return View();

        }
        public  IActionResult ChangePwd(string oldpwd,string newpwd,string newlypwd)
        {
            if (string.IsNullOrEmpty(oldpwd)) {
                throw new MessageBox("旧密码不能为空！");
            }
            if (string.IsNullOrEmpty(newpwd))
            {
                throw new MessageBox("新密码不能为空！");
            }
            if (string.IsNullOrEmpty(oldpwd))
            {
                throw new MessageBox("确认密码不能为空！");
            }
            if (string.IsNullOrEmpty(oldpwd))
            {
                throw new MessageBox("旧密码不能为空!");
            }
            _Sys_UserM = db.Find<Sys_UserM>(f => f.User_ID == Account.UserID);
            if (!_Sys_UserM.User_Pwd.Equals(oldpwd.Trim())) {

                throw new MessageBox("旧密码不正确！");
            }
            //修改
            if (!db.Edit<Sys_UserM>(() => new Sys_UserM() { User_Pwd = newlypwd }, p => p.User_ID == Account.UserID, li)) {
                throw new MessageBox(db.ErrorMessage);
            }
            
            if (!db.Commit(li)) {
                throw new MessageBox(db.ErrorMessage);
            }

            //JsonConvert.SerializeObject(new { y = 1 });

            //Sys_UserM ad= JsonConvert.DeserializeObject<Sys_UserM>(json);
            return  Json(new { status="Ok"}); 

        }

       

    }

}

AdminManagement/Areas/Admin/Controllers/Sys/CreateCodeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace AdminManagement.Areas.Admin.Controllers.Sys
{
    using BLL;
    using DbFrame.Class;
    using Common;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.AspNetCore.Http;
    public class CreateCodeController : BaseController
    {
        private readonly Sys_CreateCodeBL _Sys_CreateCodeBL = new Sys_CreateCodeBL();
        public IHostingEnvironment _ihostingEnvironment = null;
        private string _WebRootPath = string.Empty;  
        public CreateCodeController(IHostingEnvironment ihostingEnvironment) {

            this._ihostingEnvironment = ihostingEnvironment;
            _WebRootPath = this._ihostingEnvironment.WebRootPath.ToString();
        }
 
        protected override void Init()
        {
            this.MenuID = "Z-160";
        }
        public override IActionResult Index()
        {
            ViewData["Path"] = (_WebRootPath+"\\Content\\CreateFile\\").Replace("\\","\\\\");
            return base.Index();
        }
        [HttpPost]
        public ActionResult GetDatabaseAllTable() {

            return Json(new { status = 1, value = _Sys_CreateCodeBL.GetDatabaseAllTable() });
                
        }
        /// <summary>
        /// 保存代码
        /// </summary>
        /// <param name="Fc"></param>
        /// <returns></returns>
        [HttpPost]
        public ActionResult Save(IFormCollection Fc) {

            var Type = Fc["ClassType"].ToStr() ;
            var Url=(Fc["Url"].ToStr()??_WebRootPath+"\\Content\\CreateFile\\");
            var Str = Fc["Str"];
            var Table = Fc["Table"];
            var isall = Fc["isall"].ToBool();
            var template = _WebRootPath + "\\Content\\Template\\";
            if (Type == "Model") {

                Url = (Url+"\\Model");
                template = template + "Model\\Model.txt";
                Str = string.IsNullOrEmpty(Str.ToStr()) ? "M" : Str.ToStr();
            }
            else if (Type == "BLL")
            {

                Url = (Url + "\\BLL");
                template = template + "BLL\\BLL.txt";
                Str = string.IsNullOrEmpty(Str.ToStr()) ? "BLL" : Str.ToStr();
            }
            else if (Type == "DLL")
            {

                Url = (Url + "\\DLL");
                template = template + "DLL\\DLL.txt";
                Str = string.IsNullOrEmpty(Str.ToStr()) ? "DA" : Str.ToStr();
            }
            if (System.IO.Directory.Exists(Url + "\\")) {

                var dir = new System.IO.DirectoryInfo(Url + "\\");
                var fileinfo = dir.GetFileSystemInfos();//返回目录中所有文件和子目录
                foreach (var i in fileinfo) {
                    if (i is System.IO.DirectoryInfo)
                    {
                        var subdir = new System.IO.DirectoryInfo(i.FullName);
                        subdir.Delete(true);//删除子目录和文件
                    }
                    else {

                        System.IO.File.Delete(i.FullName);     
                    }
                }
            }
            System.IO.Directory.CreateDirectory(Url);
            if (!System.IO.File.Exists(template))
                throw new MessageBox("模板文件不存在！");
            var Content = System.IO.File.ReadAllText(template);
            if (isall)
            {
                var list = _Sys_CreateCodeBL.GetAllTable();
                foreach (var item in list)
                {
                    Table = item["TABLE_NAME"] == null ? "" : item["TABLE_NAME"].ToStr();
                    this._Sys_CreateCodeBL.CreateFileLogic(Content, Table, Str, Type, Url);
                }
            }
            else {
                if (string.IsNullOrEmpty(Table)) {

                    throw new MessageBox("请选择表");  
                }
                this._Sys_CreateCodeBL.CreateFileLogic(Content, Table, Str, Type, Url);

            }
            return Json(new { status="1"});
        }
    }
}

AdminManagement/Areas/Admin/Controllers/Sys/FunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AdminManagement.Areas.Admin.Controllers.Sys

{
    using global::Model;
    using BLL;
    using DbFrame.Class;
    using Common;
    using System.Collections;
    using AOP;
    using Microsoft.Extensions.Configuration;

    public class FunctionController : BaseController
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}
        Sys_FunctionBL _Sys_FunctionBL = new Sys_FunctionBL();
        protected override void Init() {

          
            this.MenuID = "Z-120";
        }
        /// <summary>
        /// 分页数据
        /// </summary>
        /// <param name="query"></param>
        /// <param name="page"></param>
        /// <param name="rows"></param>
        /// <returns></returns>
        [NonAction]
        public override Sys_PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {

            return _Sys_FunctionBL.GetDataSource(query, page, rows);
        }
        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [AopCheckEntityFilterAtttibute(new string[] { ("model") })]
        [HttpPost]
        public IActionResult Save(Sys_FunctionM model) {

            this.KeyID = _Sys_FunctionBL.Save(model);
            
            return Json(new { status = 1, ID = KeyID });

        }
        [HttpPost]
        public IActionResult Find(string ID)
        {

          return Json( _Sys_FunctionBL.Find(ID.ToGuid()));
           
        }
        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(string ID) {

            _Sys_FunctionBL.Delete(ID);

            return Json(new { status = 1 });
        }

       


    }
}

AdminManagement/Areas/Admin/Controllers/Sys/MenuFunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace AdminManagement.Areas.Admin.Controllers.Sys
{
 
    using global::Model;
    using BLL;
    using System.Collections;
    using DbFrame.Class;
    using AdminManagement.AOP;
    using System.IO;

    public class MenuFunctionController : BaseController
    {

        Sys_MenuBL _Sys_MenuBL = new Sys_MenuBL();
        protected override void Init()
        {
           
            this.MenuID = "Z-130";
        }
        [NonAction]
        public override Sys_PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            return _Sys_MenuBL.GetDataSource(query, page, rows);
        }
        /// <summary>
        /// 获取菜单和功能树
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult GetMenuAndFunctionTree()
        {
            return Json(new { status = 1, value = _Sys_MenuBL.GetMenuAndFunctionTree() });
        }
        /// <summary>
        /// 功能模块
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public IActionResult Find(string ID) {

    


            return Json(_Sys_MenuBL.Find(ID.ToGuid()));
        }

        /// <summary>
        /// 功能模块
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [AopCheckEntityFilterAtttibute(new string[] { ("model") })]
        [HttpPost] 
        public IActionResult Save(Sys_MenuM model , string Function_ID)
        {
            this.KeyID = _Sys_MenuBL.Save(model, Function_ID);
            return Json(new { status = 1, ID = KeyID });
       
        }
        [HttpPost]
        public ActionResult Delete(string ID) {

            _Sys_MenuBL.Delete(ID);
            return Json(new { status = 1 });
        }





    }
}

AdminManagement/Areas/Admin/Controllers/Sys/RoleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AdminManagement.Areas.Admin.Controllers.Sys
{
    using global::Model;
    using BLL;
    using DbFrame.Class;
    using Common;
    using System.Collections;

    public class RoleController : BaseController
    {
        //public IActionResult Index()
        Sys_RoleBL _Sys_RoleBL = new Sys_RoleBL();

        protected override void Init()
        {
            //base.Init();
            this.MenuID = "Z-110";
        }
        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="PageIndex"></param>
        /// <param name="PageSize"></param>
        /// <returns></returns>
        [NonAction]
        public override Sys_PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            return _Sys_RoleBL.GetDataSource(query, page, rows);
        }
        /// <summary>
        /// 根据ID 获取对象
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        [HttpPost]
        public IActionResult Find(string ID) {

            
            return Json(_Sys_RoleBL.Find(ID.ToGuid()));

        }
       /// <summary>
       /// 删除
       /// </summary>
       /// <param name="id"></param>
       /// <returns></returns>
        [HttpPost]
        public IActionResult Delete(string id) {

            _Sys_RoleBL.Delete(id);

            return Json(new { status=1 });
        }
        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpPost]
        [AOP.AopCheckEntityFilterAtttibute(new string[] { "model"})]
        public IActionResult Save(Sys_RoleM model )
        {
            this.KeyID = _Sys_RoleBL.Save(model);
            return Json(new { status=1, ID=KeyID });
        }
        //{
        //    return View();
        //}







    }
}

AdminManagement/Areas/Admin/Controllers/Sys/RoleFunctionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using Microsoft.AspNetCore.Mvc;

namespace AdminManagement.Areas.Admin.Controllers.Sys
{
    using BLL;
    public class RoleFunctionController : BaseController
    {
        protected override void Init()
        {
            this.MenuID = "Z-140";
        }
        Sys_RoleBL _Sys_RoleBL = new Sys_RoleBL();
        Sys_MenuBL _Sys_MenuBL = new Sys_MenuBL();

        /// <summary>
        /// 获取角色菜单功能
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        public IActionResult GetRoleMenuFunctionTree(string roleid)
        {
            return Json(new { status = 1, value = _Sys_MenuBL.GetRoleMenuFunctionTree(roleid) });
        }
        public IActionResult Save(string rows,string roleid) {

            _Sys_RoleBL.SaveFunction(rows, roleid);

            return Json(new { status = 1 });
        }

    }
}

AdminManagement/Areas/Admin/Controllers/Sys/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AdminManagement.Areas.Admin.Controllers.Sys
{
    using global::Model;
    using BLL;
    using DbFrame.Class;
    using System.Collections;
    using AOP;
    using System.IO;
    using System.Text;

    public class UserController : BaseController
    {
        Sys_UserBL _Sys_UserBL = new Sys_UserBL();

        protected override void Init()
        {
           // base.Init();
            this.MenuID = "Z-100";
        }
        //public IActionResult Index()
        //{
        //    return View();
        //}
        /// <summary>
        /// 获取列表数据
        /// </summary>
        /// <param name="query"></param>
        /// <param name="page">PageIndex</param>
        /// <param name="rows">PageSize</param>
        /// <returns></returns>
        [NonAction]   //只是普通的方法 
        public override Sys_PagingEntity GetPagingEntity(Hashtable query, int page = 1, int rows = 20)
        {
            return _Sys_UserBL.GetDataSource(query, page, rows);
        }

        #region
        [HttpPost]
        public IActionResult Find(string ID) {

            return Json(_Sys_UserBL.Find(ID.ToGuid()));
        }
        [HttpPost] 
        public IActionResult Delete(string id) {

            _Sys_UserBL.Delete(id);
            return Json(new { status = 1 });
        }
        /// <summary>
        /// 保存
        /// </summary>
        /// <param name="model"></param>
        /// <param name="Role_ID"></param>
        /// <returns></returns>

        [AopCheckEntityFilterAtttibute(new string[] { "model" })]
        [HttpPost]
        public IActionResult Save(Sys_UserM model, string Role_ID)
        {
            this.KeyID = _Sys_UserBL.Save(model, Role_ID);
            return Json(new { status = 1, ID = KeyID });
        }
        #endregion

    }
}

AdminManagement/Areas/Admin/Views/Sys/User/Index.cshtml
<div id="hzy-container">
    <div class="page-content">
        <!--高级检索部分-->
        <div class="panel" id="panelSearch">
            <div class="panel-heading">
                <h3 class="panel-title">高级检索</h3>
            </div>
            <div class="panel-body">
                <form action="javascript:void(0)">
                    <div class="col-sm-3">
                        <h4 class="example-title">用户名</h4>
                        <input type="text" class="form-control" name="User_Name" placeholder="请输入用户名">
                    </div>
                    <div class="col-sm-3">
                        <h4 class="example-title">登录名</h4>
                        <input type="text" class="form-control" name="User_LoginName" placeholder="请输入登录名">
                    </div>
                </form>
            </div>
            <div class="panel-footer text-right">
                <button class="btn btn-primary btn-outline" onclick="adminList.search()">检索</button>&nbsp;&nbsp;
                <button class="btn btn-success btn-outline" onclick="adminList.resetSearch()">重置</button>&nbsp;&nbsp;
                <button class="btn btn-danger btn-outline" onclick="adminList.panelSearch()">关闭</button>
            </div>
        </div>
        <!--列表部分-->
        <div class="panel">
            <div class="panel-body" style="padding: 10px;padding-bottom:0;">

                <div class="row">
                    <div class="col-sm-12">
                        <div class="btn-group">
                            <button type="button" class="btn btn-default btn-outline" onclick="window.location=window.location">
                                <i class="fa fa-rotate-right"></i>&nbsp;刷新
                            </button>
                            <button type="button" class="btn btn-default btn-outline" data-power="Search" name="search" onclick="adminList.panelSearch()">
                                <i class="fa fa-search"></i>&nbsp;检索
                            </button>
                            <button type="button" class="btn btn-default btn-outline" data-power="Add" name="add" onclick="App.Form('add')">
                                <i class="fa fa-plus"></i>&nbsp;添加
                            </button>
                            <button type="button" class="btn btn-default btn-outline" data-power="Edit" name="edit" onclick="App.Form('edit')" disabled="disabled">
                                <i class="fa fa-pencil"></i>&nbsp;修改
                            </button>
                            <button type="button" class="btn btn-default btn-outline" data-power="Delete" name="delete" onclick="App.Delete()" disabled="disabled">
                                <i class="fa fa-trash"></i>&nbsp;删除
                            </button>
                            <a class="btn btn-default btn-outline" target="_blank" href="" data-power="GetExcel" name="getExcel" onclick="App.ExportExcel()">
                                <i class="fa fa-file-excel-o"></i>&nbsp;导出 Excel
                            </a>
                        </div>
                    </div>
                    <div class="col-sm-12 margin-top-5">
                        <!--表格-->
                        <table class="table table-bordered table-hover" id="bootStrapTable"></table>
                    </div>
                </div>

            </div>
        </div>

    </div>
</div>
@section css{

    <link href="~/Admin/lib/bootstrap-table-develop/src/bootstrap-table.css" rel="stylesheet" />
}

@section js{

    <script src="~/Admin/lib/bootstrap-table-develop/src/bootstrap-table.js"></script>
    <script src="~/Admin/lib/bootstrap-table-develop/src/locale/bootstrap-table-zh-CN.js"></script>
    <script src="~/Admin/js/admin-list.js"></script>
    <script type="text/javascript">

        var FormID="@ViewData["formWindowName"]";

        var thisWindowName = "@ViewData["thisWindowName"]";
     
        $(function () {
            App.Init();
        });
        var App = {
            Init: function () {
                admin.ajax({
                    url: "@Url.Action("GetDataSource")",
                    data: { rows: 1 },
                    success: function (r) {
                        var adminBootStrapTable = adminList.bootStrapTable({
                            url: "@Url.Action("GetDataSource")",
                            columns: r.column
                        });
                    }
                });
            },
            Form: function(tag){
                var rows = adminList.selectRows();
              
                    adminList.form({
                    id: FormID,
                    parentIframeName: thisWindowName,
                    url: "@Url.Action("Info")" + (tag == "add" ? "" : "/?ID=" + rows[0]._ukid),
                    width: "500px",
                    height: "600px",
                    btn: false,
                   
                });
            },
            Delete: function () {

                 adminList.delete('@Url.Action("Delete")', function () {
                    App.Refresh();
                    console.log("删除完成！");
                })
            },
            Refresh: function (data) {

                adminList.refresh(data);  
            }, 
            ExportExcel: function () {

                adminList.exportExcel('@Url.Action("ExportExcel")');
            }
        };

    </script>

}

AdminManagement/Areas/Admin/Views/Sys/User/Info.cshtml
@{
    var KeyId = Tools.HttpHelper.Request.Query["ID"];
}
<div class="page-content animated fadeInDown">
    <div class="container-fluid" style="padding-bottom:100px;">
        <div class="row" id="form">
            <!--检索面板-->
            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">用户名</h4>
                <input type="text" class="form-control" name="User_Name" data-bind="value:User_Name" placeholder="请输入用户名" />
            </div>
            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">登录名</h4>
                <input type="text" class="form-control" name="User_LoginName" data-bind="value:User_LoginName" placeholder="请输入登录名" />
            </div>
            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">登录密码</h4>
                <input type="password" class="form-control" name="User_Pwd"   data-bind="value:User_Pwd" placeholder="请输入登录密码" />
            </div>
            <div class="col-sm-6 col-md-4">
                <h4 class="example-title">邮箱地址</h4>
                <input type="text" class="form-control" name="User_Email" data-bind="value:User_Email" placeholder="请输入邮件" />
            </div>
           
            @(UI.FindBack<Sys_RoleM, Sys_RoleM>(
                                w => w.Role_Name, w => w.Role_ID,
                                Url.Action("Index", "Role", new { findback = "1" }),
                                "App.FindBack.CallBack(row,'Role')",
                                "App.FindBack.CallBack(null,'Role');"
            ))
        </div>
    </div>

</div>
<!--按钮-->
<div class="my-ButtonBar text-right">
    <div class="btn-group">
        <button type="button" class="btn btn-success btn-outline" data-bind="visible: !App.IsAdd()" onclick="adminForm.resetUrl(null)">新增</button>
        <button class="btn btn-primary btn-outline" onclick="App.Save()">提交</button>
        <button class="btn btn-danger btn-outline" onclick="admin.layer.close(admin.getLayerIframeIndex());">关闭</button>
    </div>
</div>
@section css{
}
@section js{
    <script src="~/Admin/lib/Ko/Knockout-3.4.2.debug.js"></script>
    <script src="~/Admin/js/admin-form.js"></script>
    <script type="text/javascript">
        var KeyId = '@KeyId';
        model = new vModel();
        $(function () {
            ko.applyBindings(model);//注册vModel
            
            App.Load();
        });

        var App = {
            IsAdd: function () {
                return !KeyId;
            },
            Load: function () {
               
                adminForm.load({
                   
                    KeyId: KeyId,
                    url: "@Url.Action("Find")",
                    callBack: function (r) {

                    }
                });
            },
            Save: function () {
                adminForm.Save({
                    url: "@Url.Action("Save")"

                });


            },
            ExportExcel: function () {

                adminList.exportExcel('@Url.Action("ExportExcle")');
            },

           FindBack: {
                CallBack: function (row, tag, dom) {
                    if (row != null && row.length > 0) row = row[0];

                    if (tag == "Role") {

                        model.Role_ID(row ? row._ukid : "");

                        model.Role_Name(row ? row.Role_Name : "");
                    }
                }
            }
        };
        //User_ID, User_Name, User_LoginName, User_Pwd, User_Email, User_CreateTime
         function vModel() { @(UI.CreateKOViewModel(new Sys_UserM(),new Sys_RoleM()))
            // this.User_ID = ko.observable("");
            //this.User_Name = ko.observable("");
            //this.User_LoginName = ko.observable("");
            //this.User_Pwd = ko.observable("");
            //this.User_Email = ko.observable("");

            //this.Role_ID = ko.observable("");
            //this.Role_Name = ko.observable("");
        }
    </script>
}